# Use an official lightweight Python image
FROM python:3.10-slim

# Set the working directory
WORKDIR /app

# Copy dependency list first (to leverage Docker caching)
COPY . /app

# Install dependencies (no cache to keep image small)
RUN pip install flask

# Copy application code
EXPOSE 5000

# Default command (run app.py)
CMD ["python", "app.py"]
